# Generated by Django 4.2.7 on 2026-01-18 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('reason', models.CharField(choices=[('expired', 'Истёк срок годности'), ('damaged', 'Повреждено'), ('quality', 'Несоответствие качеству'), ('other', 'Другое')], max_length=20, verbose_name='Причина списания')),
                ('reason_detail', models.TextField(blank=True, verbose_name='Детали')),
                ('write_off_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата списания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_offs', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Списание',
                'verbose_name_plural': 'Списания',
                'ordering': ['-write_off_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.IntegerField(verbose_name='Ожидаемое количество')),
                ('actual_quantity', models.IntegerField(verbose_name='Фактическое количество')),
                ('difference', models.IntegerField(verbose_name='Разница')),
                ('inventory_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата инвентаризации')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проводил')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'ordering': ['-inventory_date'],
            },
        ),
    ]
