# Generated by Django 4.2.7 on 2026-01-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='session_id',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='ID сессии'),
            preserve_default=False,
        ),
    ]
